"""empty message

Revision ID: 481fc945faf0
Revises: 584970bfe937
Create Date: 2017-12-10 22:09:09.157141

"""

# revision identifiers, used by Alembic.
revision = '481fc945faf0'
down_revision = '584970bfe937'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
