"""empty message

Revision ID: 584970bfe937
Revises: 4534f958ebd9
Create Date: 2017-12-10 19:16:57.262973

"""

# revision identifiers, used by Alembic.
revision = '584970bfe937'
down_revision = '4534f958ebd9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
