"""firich text

Revision ID: 79d4ab0cdbd6
Revises: 851e988a52f8
Create Date: 2017-12-11 19:46:47.622159

"""

# revision identifiers, used by Alembic.
revision = '79d4ab0cdbd6'
down_revision = '851e988a52f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
