"""throrough 11a

Revision ID: 851e988a52f8
Revises: 481fc945faf0
Create Date: 2017-12-11 18:01:10.451575

"""

# revision identifiers, used by Alembic.
revision = '851e988a52f8'
down_revision = '481fc945faf0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
