"""empty message

Revision ID: a4bf599ab08b
Revises: aeece849327a
Create Date: 2017-12-17 22:26:14.174709

"""

# revision identifiers, used by Alembic.
revision = 'a4bf599ab08b'
down_revision = 'aeece849327a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('institution', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('study_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('study_objective', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'study_objective')
    op.drop_column('users', 'study_name')
    op.drop_column('users', 'institution')
    # ### end Alembic commands ###
