"""empty message

Revision ID: aeece849327a
Revises: 79d4ab0cdbd6
Create Date: 2017-12-15 15:03:26.851279

"""

# revision identifiers, used by Alembic.
revision = 'aeece849327a'
down_revision = '79d4ab0cdbd6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=64), nullable=True),
    sa.Column('study_name', sa.String(length=255), nullable=True),
    sa.Column('study_objective', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consents')
    # ### end Alembic commands ###
