"""empty message

Revision ID: efddf94d54cf
Revises: 3b8912080692
Create Date: 2017-12-04 23:50:59.382362

"""

# revision identifiers, used by Alembic.
revision = 'efddf94d54cf'
down_revision = '3b8912080692'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
